//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLog
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string RefUserName { get; set; }
        public string RefSubverse { get; set; }
        public string RefUrl { get; set; }
        public Nullable<int> RefCommentID { get; set; }
        public Nullable<int> RefSubmissionID { get; set; }
        public string Type { get; set; }
        public string Action { get; set; }
        public string Details { get; set; }
        public string InternalDetails { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
