//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiCorsPolicy
    {
        public int ID { get; set; }
        public bool IsActive { get; set; }
        public string AllowOrigin { get; set; }
        public string AllowMethods { get; set; }
        public string AllowHeaders { get; set; }
        public Nullable<bool> AllowCredentials { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
