//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoModSubmission
    {
        public int ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string RuleAuthor { get; set; }
        public string ActionToTake { get; set; }
        public string SubmissionTitle { get; set; }
        public string SubmissionDomain { get; set; }
        public string SubmissionAuthor { get; set; }
        public Nullable<int> SubmissionType { get; set; }
        public string SubmissionText { get; set; }
        public Nullable<int> MinAuthorAccountAgeInDays { get; set; }
        public Nullable<int> MinAuthorCCP { get; set; }
        public Nullable<int> MinAuthorSCP { get; set; }
        public Nullable<int> MinBodyLength { get; set; }
        public Nullable<int> MaxBodyLength { get; set; }
        public string AutoComment { get; set; }
        public string AutoModPM { get; set; }
        public string AutoAuthorPM { get; set; }
        public Nullable<bool> NotifyAuthor { get; set; }
        public Nullable<bool> NotifyMod { get; set; }
        public Nullable<bool> CheckEdited { get; set; }
    }
}
