//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentReplyNotification
    {
        public int ID { get; set; }
        public int CommentID { get; set; }
        public int SubmissionID { get; set; }
        public string Recipient { get; set; }
        public string Sender { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsUnread { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool MarkedAsUnread { get; set; }
        public string Subverse { get; set; }
    }
}
