//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.IsDeleted = false;
            this.Commentsavingtrackers = new HashSet<Commentsavingtracker>();
            this.Commentvotingtrackers = new HashSet<Commentvotingtracker>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Votes { get; set; }
        public string Name { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<int> MessageId { get; set; }
        public int Likes { get; set; }
        public int Dislikes { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool Anonymized { get; set; }
        public bool IsDistinguished { get; set; }
        public string FormattedContent { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CommentRemovalLog CommentRemovalLog { get; set; }
        public virtual Message Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentsavingtracker> Commentsavingtrackers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentvotingtracker> Commentvotingtrackers { get; set; }
    }
}
