//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string UserName { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public bool IsBase { get; set; }
        public string CallStack { get; set; }
        public string Data { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Origin { get; set; }
    }
}
