//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Featuredsub
    {
        public int Feature_id { get; set; }
        public string Subname { get; set; }
        public string Featured_by { get; set; }
        public System.DateTime Featured_on { get; set; }
    
        public virtual Subverse Subverse { get; set; }
    }
}
