//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.IsDeleted = false;
            this.Comments = new HashSet<Comment>();
            this.Savingtrackers = new HashSet<Savingtracker>();
            this.Viewstatistics = new HashSet<Viewstatistic>();
            this.Votingtrackers = new HashSet<Votingtracker>();
        }
    
        public int Id { get; set; }
        public bool IsArchived { get; set; }
        public Nullable<int> Votes { get; set; }
        public string Name { get; set; }
        public string MessageContent { get; set; }
        public System.DateTime Date { get; set; }
        public int Type { get; set; }
        public string Linkdescription { get; set; }
        public string Title { get; set; }
        public double Rank { get; set; }
        public string Subverse { get; set; }
        public int Likes { get; set; }
        public int Dislikes { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string FlairLabel { get; set; }
        public string FlairCss { get; set; }
        public bool Anonymized { get; set; }
        public double Views { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Subverse Subverses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Savingtracker> Savingtrackers { get; set; }
        public virtual Stickiedsubmission Stickiedsubmission { get; set; }
        public virtual SubmissionRemovalLog SubmissionRemovalLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viewstatistic> Viewstatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Votingtracker> Votingtrackers { get; set; }
    }
}
