//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerInformation
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PartnerPaymentForm { get; set; }
        public string PartnerBankAccountNumber { get; set; }
        public string PartnerNameOfAccountHolder { get; set; }
        public string PartnerSwiftCode { get; set; }
        public string PartnerBankName { get; set; }
        public string PartnerIFSC { get; set; }
        public string PartnerBIK { get; set; }
        public string PartnerPaymentCurrency { get; set; }
        public string PartnerPhoneNumber { get; set; }
        public string PartnerPayeeName { get; set; }
        public string PartnerCity { get; set; }
        public string PartnerCountry { get; set; }
        public string PartnerZip { get; set; }
        public string PartnerStreet { get; set; }
        public System.DateTime PartnerLastPaymentDate { get; set; }
    }
}
