//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleReport
    {
        public long ID { get; set; }
        public string Subverse { get; set; }
        public string UserName { get; set; }
        public Nullable<int> SubmissionID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int RuleSetID { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
    
        public virtual RuleSet RuleSet { get; set; }
    }
}
