//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubverseAdmin
    {
        public int Id { get; set; }
        public string SubverseName { get; set; }
        public string Username { get; set; }
        public int Power { get; set; }
        public string Added_by { get; set; }
        public Nullable<System.DateTime> Added_on { get; set; }
    
        public virtual Subverse Subverse { get; set; }
    }
}
