//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subverse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subverse()
        {
            this.Featuredsubs = new HashSet<Featuredsub>();
            this.Messages = new HashSet<Message>();
            this.Stickiedsubmissions = new HashSet<Stickiedsubmission>();
            this.Subscriptions = new HashSet<Subscription>();
            this.SubverseAdmins = new HashSet<SubverseAdmin>();
            this.SubverseBans = new HashSet<SubverseBan>();
            this.Subverseflairsettings = new HashSet<Subverseflairsetting>();
            this.UserBlockedSubverses = new HashSet<UserBlockedSubverse>();
            this.Usersetdefinitions = new HashSet<Usersetdefinition>();
        }
    
        public string name { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string sidebar { get; set; }
        public string submission_text { get; set; }
        public string language { get; set; }
        public string type { get; set; }
        public string label_submit_new_link { get; set; }
        public string label_sumit_new_selfpost { get; set; }
        public string spam_filter_links { get; set; }
        public string spam_filter_selfpost { get; set; }
        public string spam_filter_comments { get; set; }
        public bool rated_adult { get; set; }
        public bool allow_default { get; set; }
        public bool enable_thumbnails { get; set; }
        public bool exclude_sitewide_bans { get; set; }
        public Nullable<bool> traffic_stats_public { get; set; }
        public Nullable<int> minutes_to_hide_comments { get; set; }
        public System.DateTime creation_date { get; set; }
        public string stylesheet { get; set; }
        public Nullable<int> subscribers { get; set; }
        public bool private_subverse { get; set; }
        public bool authorized_submitters_only { get; set; }
        public bool anonymized_mode { get; set; }
        public Nullable<System.DateTime> last_submission_received { get; set; }
        public int minimumdownvoteccp { get; set; }
        public bool forced_private { get; set; }
        public Nullable<bool> admin_disabled { get; set; }
    
        public virtual Defaultsubverse Defaultsubvers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Featuredsub> Featuredsubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stickiedsubmission> Stickiedsubmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubverseAdmin> SubverseAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubverseBan> SubverseBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subverseflairsetting> Subverseflairsettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBlockedSubverse> UserBlockedSubverses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usersetdefinition> Usersetdefinitions { get; set; }
    }
}
