//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public bool DisableCSS { get; set; }
        public bool NightMode { get; set; }
        public string Language { get; set; }
        public bool OpenInNewWindow { get; set; }
        public bool EnableAdultContent { get; set; }
        public bool DisplayVotes { get; set; }
        public bool DisplaySubscriptions { get; set; }
        public bool UseSubscriptionsMenu { get; set; }
        public string Bio { get; set; }
        public string Avatar { get; set; }
        public string UserName { get; set; }
    }
}
