//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetSubscription
    {
        public int ID { get; set; }
        public int UserSetID { get; set; }
        public int Order { get; set; }
        public string UserName { get; set; }
    
        public virtual UserSet UserSet { get; set; }
    }
}
