//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiClient
    {
        public int ID { get; set; }
        public bool IsActive { get; set; }
        public string UserName { get; set; }
        public string AppName { get; set; }
        public string AppDescription { get; set; }
        public string AppAboutUrl { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ApiThrottlePolicyID { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        public Nullable<int> ApiPermissionPolicyID { get; set; }
        public string RedirectUrl { get; set; }
    
        public virtual ApiPermissionPolicy ApiPermissionPolicy { get; set; }
        public virtual ApiThrottlePolicy ApiThrottlePolicy { get; set; }
    }
}
