//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banneddomain
    {
        public int Id { get; set; }
        public string Hostname { get; set; }
        public string Added_by { get; set; }
        public System.DateTime Added_on { get; set; }
        public string Reason { get; set; }
    }
}
