//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whoaverse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postreplynotification
    {
        public int Id { get; set; }
        public int CommentId { get; set; }
        public int SubmissionId { get; set; }
        public string Recipient { get; set; }
        public string Sender { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool Status { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool Markedasunread { get; set; }
        public string Subverse { get; set; }
    }
}
