//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whoaverse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subverse
    {
        public Subverse()
        {
            this.subscribers = 1;
            this.Messages = new HashSet<Message>();
            this.SubverseAdmins = new HashSet<SubverseAdmin>();
        }
    
        public string name { get; set; }
        public string title { get; set; }
        public string sidebar { get; set; }
        public string submission_text { get; set; }
        public string language { get; set; }
        public string type { get; set; }
        public string label_submit_new_link { get; set; }
        public string label_sumit_new_selfpost { get; set; }
        public string spam_filter_links { get; set; }
        public string spam_filter_selfpost { get; set; }
        public string spam_filter_comments { get; set; }
        public Nullable<bool> rated_adult { get; set; }
        public Nullable<bool> allow_default { get; set; }
        public Nullable<bool> enable_thumbnails { get; set; }
        public Nullable<bool> exclude_sitewide_bans { get; set; }
        public Nullable<bool> traffic_stats_public { get; set; }
        public Nullable<int> minutes_to_hide_comments { get; set; }
        public System.DateTime creation_date { get; set; }
        public string description { get; set; }
        public string stylesheet { get; set; }
        public Nullable<int> subscribers { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Defaultsubverse Defaultsubvers { get; set; }
        public virtual ICollection<SubverseAdmin> SubverseAdmins { get; set; }
    }
}
