//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubverseBan
    {
        public int Id { get; set; }
        public string SubverseName { get; set; }
        public string Username { get; set; }
        public string BannedBy { get; set; }
        public System.DateTime BanAddedOn { get; set; }
        public string BanReason { get; set; }
    
        public virtual Subverse Subverse { get; set; }
    }
}
