//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnreadNotificationCount
    {
        public string UserName { get; set; }
        public Nullable<int> PrivateMessages { get; set; }
        public Nullable<int> CommentReplies { get; set; }
        public Nullable<int> PostReplies { get; set; }
    }
}
