//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userbadge
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string BadgeId { get; set; }
        public System.DateTime Awarded { get; set; }
    
        public virtual Badge Badge { get; set; }
    }
}
