//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userset
    {
        public Userset()
        {
            this.Usersetdefinitions = new HashSet<Usersetdefinition>();
            this.Usersetsubscriptions = new HashSet<Usersetsubscription>();
        }
    
        public int Set_id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Created_by { get; set; }
        public System.DateTime Created_on { get; set; }
        public bool Public { get; set; }
        public int Subscribers { get; set; }
    
        public virtual ICollection<Usersetdefinition> Usersetdefinitions { get; set; }
        public virtual ICollection<Usersetsubscription> Usersetsubscriptions { get; set; }
    }
}
