//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whoaverse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Votingtracker
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> VoteStatus { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
