//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voat.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SubmissionRemovalLog
    {
        public int SubmissionID { get; set; }
        public string Moderator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Reason { get; set; }

        [NotMapped] //CORE_PORT: This seems to have EF CORE generate a SubmissionID1 column on inserts. See unit test: DeleteSubmission_Moderator 
        public Submission Submission { get; set; }
    }
}
